/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_maye_IVI_MainActivity_MyTask */

#ifndef _Included_com_example_maye_IVI_MainActivity_MyTask
#define _Included_com_example_maye_IVI_MainActivity_MyTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_maye_IVI_MainActivity_MyTask_VIRGIN
#define com_example_maye_IVI_MainActivity_MyTask_VIRGIN 0L
#undef com_example_maye_IVI_MainActivity_MyTask_SCHEDULED
#define com_example_maye_IVI_MainActivity_MyTask_SCHEDULED 1L
#undef com_example_maye_IVI_MainActivity_MyTask_EXECUTED
#define com_example_maye_IVI_MainActivity_MyTask_EXECUTED 2L
#undef com_example_maye_IVI_MainActivity_MyTask_CANCELLED
#define com_example_maye_IVI_MainActivity_MyTask_CANCELLED 3L
#ifdef __cplusplus
}
#endif
#endif
