/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_maye_IVI_MainActivity_GuiInfo */

#ifndef _Included_com_example_maye_IVI_MainActivity_GuiInfo
#define _Included_com_example_maye_IVI_MainActivity_GuiInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
