/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_maye_jnitest_MainActivity */

#ifndef _Included_com_example_maye_jnitest_MainActivity
#define _Included_com_example_maye_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_maye_jnitest_MainActivity
 * Method:    StringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_maye_jnitest_MainActivity_StringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
