/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_maye_IVI_MainActivity_IpPacket */

#ifndef _Included_com_example_maye_IVI_MainActivity_IpPacket
#define _Included_com_example_maye_IVI_MainActivity_IpPacket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
